# Generated by Django 4.0.3 on 2022-08-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
